services:
  postgres_db:
    image: postgres:17-alpine
    container_name: odin-oss-psql
    restart: always
    environment:
      POSTGRES_USER: odin
      POSTGRES_PASSWORD: odin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: