# Project key, name, and version
sonar.projectKey=MONOLITH-API
sonar.projectName=MONOLITH-API
sonar.projectVersion=1.0

# The source code and test folders
sonar.sources=src
sonar.tests=test
sonar.exclusions=**/*.test.js
sonar.coverage.exclusions=src/routes/*.route.js, src/routes/**/*.route.js, src/config/*.js, src/modules/router.module.js, src/utils/health.service.js
sonar.test.inclusions=**/*.test.js
sonar.scm.forceReloadAll=true
# To enable the collection of unit tests results
#sonar.testExecutionReportPaths=sonar-reports/test-report.xml

# The language used by the project (for example JavaScript)
sonar.language=js

# Test coverage and test results report (for Jasmine)
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.token=sqp_048ba7cd17bd6833b0bedb1aad8265024b25a5ef
sonar.host.url=http://localhost:9000

